apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexzhenyul/online-boutique-devsecops
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # No automated — prod requires manual approval